name: Generate Pac-Man Contribution Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pac-Man SVGs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          output_dir: output

      - name: Commit and push SVGs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Pac-Man graph"
          file_pattern: output/*.svg
          branch: output
